CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_PMW3610_ALT=y
CONFIG_ZMK_MOUSE=y
CONFIG_ZMK_EXT_POWER=y
CONFIG_LOG=y
CONFIG_PMW3610_ALT_LOG_LEVEL_DBG=y
CONFIG_PMW3610_REST3_SAMPLE_TIME_MS=300
CONFIG_PMW3610_RUN_DOWNSHIFT_TIME_MS=500
CONFIG_PMW3610_REST1_DOWNSHIFT_TIME_MS=3000
CONFIG_PMW3610_REST2_DOWNSHIFT_TIME_MS=30000
CONFIG_PMW3610_MACCEL=y
CONFIG_PMW3610_MACCEL_TAKEOFF=200
CONFIG_PMW3610_MACCEL_GROWTH_RATE=025
CONFIG_PMW3610_MACCEL_OFFSET=220
CONFIG_PMW3610_MACCEL_LIMIT=020
